# Generated by Django 4.0.5 on 2022-06-13 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plot_management', '0002_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_complete', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('member_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plot_management.profile')),
            ],
        ),
        migrations.CreateModel(
            name='OfflinePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_number', models.CharField(max_length=255, unique=True)),
                ('account_no', models.CharField(max_length=255)),
                ('member_nid', models.CharField(max_length=200)),
                ('plot_no', models.CharField(max_length=199)),
                ('road_no', models.CharField(max_length=199)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('member_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plot_management.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_firstname', models.CharField(max_length=200)),
                ('member_lastname', models.CharField(max_length=200)),
                ('member_nid', models.CharField(max_length=200)),
                ('member_phone', models.CharField(max_length=200)),
                ('member_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plot_management.profile')),
                ('member_status', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='plot_management.status')),
            ],
        ),
    ]
