# Generated by Django 4.0.5 on 2022-06-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot_management', '0004_roadnumber_plotposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnetimeMembershipPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=199)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='onetime_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='payment_range',
            field=models.CharField(default=10, max_length=200),
            preserve_default=False,
        ),
    ]
