# Generated by Django 4.0.5 on 2022-06-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot_management', '0006_alter_member_member_nid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_firstname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_lastname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_nid',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
