# Generated by Django 4.0.5 on 2022-06-14 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plot_management', '0008_alter_member_member_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plot_management.profile'),
        ),
    ]
