# Generated by Django 4.0.5 on 2022-06-15 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plot_management', '0010_alter_member_member_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_firstname', models.CharField(blank=True, max_length=200, null=True)),
                ('admin_lastname', models.CharField(blank=True, max_length=200, null=True)),
                ('admin_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('admin_nid', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('admin_email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
