# Generated by Django 4.0.5 on 2022-06-15 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plot_management', '0011_adminuserinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDateFix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackMembershipPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_email', models.CharField(blank=True, max_length=255, null=True)),
                ('member_status', models.CharField(blank=True, max_length=199, null=True)),
                ('plot_no', models.CharField(blank=True, max_length=155, null=True)),
                ('road_no', models.CharField(blank=True, max_length=155, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='member_email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plot_management.profile'),
        ),
        migrations.AlterField(
            model_name='offlinepayment',
            name='plot_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plot_management.plotposition'),
        ),
        migrations.AlterField(
            model_name='offlinepayment',
            name='road_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plot_management.roadnumber'),
        ),
        migrations.CreateModel(
            name='TrackPlotOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('owner_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plot_management.member')),
                ('plot_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plot_management.plotposition')),
                ('road_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plot_management.roadnumber')),
            ],
        ),
    ]
