# Generated by Django 4.0.5 on 2022-06-16 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plot_management', '0012_paymentdatefix_trackmembershippayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinepayment',
            name='paid_amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='offlinepayment',
            name='member_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plot_management.member'),
        ),
        migrations.AlterField(
            model_name='paymentstatus',
            name='member_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plot_management.member'),
        ),
        migrations.AlterField(
            model_name='paymentstatus',
            name='payment_complete',
            field=models.BooleanField(default=True),
        ),
    ]
