# Generated by Django 4.0.5 on 2022-06-16 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plot_management', '0013_offlinepayment_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='default_email',
            field=models.CharField(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plot_management.profile'), max_length=255),
        ),
    ]
