# Generated by Django 4.0.5 on 2022-06-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot_management', '0014_member_default_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='default_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
