# Generated by Django 4.0.5 on 2022-06-16 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plot_management', '0017_rename_admin_email_adminuserinfo_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminuserinfo',
            old_name='email',
            new_name='admin_email',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='prouser',
            new_name='email',
        ),
    ]
