# Generated by Django 4.0.5 on 2022-06-16 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plot_management', '0019_plotnumber_alter_member_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plot_management.profile'),
        ),
    ]
