# Generated by Django 4.0.5 on 2022-06-17 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plot_management', '0022_alter_member_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member_status',
        ),
    ]
