# Generated by Django 4.0.5 on 2022-06-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot_management', '0023_remove_member_member_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotposition',
            name='plot_no',
            field=models.CharField(blank=True, max_length=199, null=True, unique=True),
        ),
    ]
