# Generated by Django 4.0.5 on 2022-06-17 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plot_management', '0024_alter_plotposition_plot_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinepayment',
            name='member_status',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='plot_management.status'),
        ),
        migrations.AddField(
            model_name='trackplotownership',
            name='member_status',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='plot_management.status'),
        ),
        migrations.AlterField(
            model_name='offlinepayment',
            name='plot_no',
            field=models.CharField(blank=True, max_length=199, null=True),
        ),
        migrations.AlterField(
            model_name='offlinepayment',
            name='road_no',
            field=models.CharField(blank=True, max_length=199, null=True),
        ),
        migrations.AlterField(
            model_name='trackplotownership',
            name='plot_no',
            field=models.CharField(blank=True, max_length=199, null=True),
        ),
        migrations.AlterField(
            model_name='trackplotownership',
            name='road_no',
            field=models.CharField(blank=True, max_length=199, null=True),
        ),
    ]
