# Generated by Django 4.0.5 on 2022-06-17 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plot_management', '0025_offlinepayment_member_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackplotownership',
            name='owner_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plot_management.member'),
        ),
    ]
