# Generated by Django 4.0.5 on 2022-06-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot_management', '0029_alter_offlinepayment_member_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlinepayment',
            name='account_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='offlinepayment',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='offlinepayment',
            name='member_nid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
