# Generated by Django 4.0.5 on 2022-06-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot_management', '0030_alter_offlinepayment_account_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlinepayment',
            name='member_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='offlinepayment',
            name='member_status',
            field=models.CharField(blank=True, default=3, max_length=199, null=True),
        ),
    ]
