# Generated by Django 4.0.5 on 2022-06-19 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plot_management', '0032_alter_offlinepayment_member_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentDateFix',
        ),
    ]
