# Generated by Django 4.0.5 on 2022-06-21 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plot_management', '0038_alter_trackmembershippayment_member_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackmembershippayment',
            name='member_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plot_management.offlinepayment'),
        ),
    ]
