# Generated by Django 4.0.5 on 2022-06-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot_management', '0041_payonline'),
    ]

    operations = [
        migrations.AddField(
            model_name='payonline',
            name='medium',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payonline',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
