# Generated by Django 4.0.5 on 2022-06-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot_management', '0044_trackmembershippayment_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_email', models.CharField(blank=True, max_length=199, null=True)),
                ('plot_no', models.CharField(blank=True, max_length=199, null=True)),
                ('road_no', models.CharField(blank=True, max_length=199, null=True)),
                ('member_status', models.CharField(blank=True, max_length=199, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
