# Generated by Django 4.0.5 on 2022-07-09 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plot_management', '0046_memberhistory_member_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimemembershippayment',
            name='account_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='onetimemembershippayment',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='onetimemembershippayment',
            name='member_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plot_management.member', unique=True),
        ),
        migrations.AddField(
            model_name='onetimemembershippayment',
            name='member_nid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
