# Generated by Django 4.0.5 on 2022-07-09 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plot_management', '0047_onetimemembershippayment_account_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimemembershippayment',
            name='member_email',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plot_management.member'),
        ),
    ]
