# Generated by Django 4.0.5 on 2022-07-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot_management', '0052_alter_onetimemembershippayment_member_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackDueTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_email', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('plot_no', models.CharField(blank=True, max_length=100, null=True)),
                ('member_status', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
