# Generated by Django 4.0.5 on 2022-07-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot_management', '0053_trackduetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackduetable',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
